### ISSUE TITLE
FUS Now Requires a Valid IMEI or Serial Number

### ISSUE THREAD

**Issue by TheRealMrWicked** [jesec/SamFirm.NET#6]
Once again Samsung has made changes now requiring a valid IMEI or Serial number to download Firmware from their servers.

Bifrost has been updated and works properly, see [this commit](https://github.com/zacharee/SamloaderKotlin/commit/b1d003065835d15e9445b3bd53cf50183274e275) for the implementation.

Im also mentioning @ananjaser1211 because it seems like he is the de-facto maintainer of this project.

Thank you - MrWicked

**Comment by ananjaser1211** [comment]
Ive updated my fork and released binaries, added a field (-i) for IMEI

https://github.com/ananjaser1211/SamFirm.NET/releases/tag/v1.3.0

IMEI must match whatever model you want to download, i found that getting IMEIs from swappa lets me download arbitrarily.

and worth mentioning that IMEI/MODEL are not tied to CSC it seems, i was able to download EUX and BTE regions of a device with a generic IMEI it had

![Test](https://github.com/jesec/SamFirm.NET/assets/25624482/2c215d42-0ef8-41e8-b485-a05fed509c75)

Credit goes to @corsicanu , [zacharee](https://github.com/zacharee) and [chenxiaolong](https://github.com/chenxiaolong) for their research, i just implemented it here and my other forks.

**Comment by TheRealMrWicked** [comment]
Okay just tested and it works on my end, thank you for the fix.

Also @jesec I personally think that you should add @ananjaser1211 as a maintainer of the main repository, if he wants too that is.
